=== wang-shun/groundwork-trunk/groundwork-monitor-platform/monitor-apps/statusviewer/src/main/webapp/FilterSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Coopyright (C) 2009 GroundWork Open Source, Inc. (GroundWork)
    All rights reserved. This program is free software; you can redistribute
    it and/or modify it under the terms of the GNU General Public License
    version 2 as published by the Free Software Foundation.
   
    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.
  
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns="gwos:filter" targetNamespace="gwos:filter">
	<xsd:element name="Filters" type="Filters" />
	<xsd:complexType name="Filters">
		<xsd:sequence>
			<xsd:element name="HostFilter" type="HostFilter"
				minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="ServiceFilter" type="ServiceFilter"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="HostFilter">
		<xsd:all>
			<xsd:element name="Name" type="xsd:string" minOccurs="1"
				maxOccurs="1" nillable="false" />
			<xsd:element name="Label" type="xsd:string" minOccurs="1"
				maxOccurs="1" nillable="false" />
			<xsd:element name="MonitorStatus" minOccurs="1"
				maxOccurs="1" nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="DOWN" />
						<xsd:enumeration value="UNREACHABLE" />
						<xsd:enumeration value="UP" />
						<xsd:enumeration value="PENDING" />
						<xsd:enumeration value="SCHEDULED DOWN" />
						<xsd:enumeration value="UNSCHEDULED DOWN" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Property" type="HostProperty"
				minOccurs="1" maxOccurs="1" nillable="false" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="ServiceFilter">
		<xsd:all>
			<xsd:element name="Name" type="xsd:string" minOccurs="1"
				maxOccurs="1" nillable="false" />
			<xsd:element name="Label" type="xsd:string" minOccurs="1"
				maxOccurs="1" nillable="false" />
			<xsd:element name="MonitorStatus" minOccurs="1"
				maxOccurs="1" nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="OK" />
						<xsd:enumeration value="CRITICAL" />
						<xsd:enumeration value="UNKNOWN" />
						<xsd:enumeration value="WARNING" />
						<xsd:enumeration value="PENDING" />
						<xsd:enumeration value="SCHEDULED CRITICAL" />
						<xsd:enumeration value="UNSCHEDULED CRITICAL" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Property" type="ServiceProperty"
				minOccurs="1" maxOccurs="1" nillable="false" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="HostProperty">
		<xsd:all>
			<xsd:element name="Name" minOccurs="1" maxOccurs="1"
				nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="isAcknowledged" />
						<xsd:enumeration value="timeDown" />
						<xsd:enumeration value="timeUp" />
						<xsd:enumeration value="timeUnreachable" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Type" minOccurs="1" maxOccurs="1"
				nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="String" />
						<xsd:enumeration value="Boolean" />
						<xsd:enumeration value="Long" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Value" minOccurs="1" maxOccurs="1"
				nillable="true">
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="ServiceProperty">
		<xsd:all>
			<xsd:element name="Name" minOccurs="1" maxOccurs="1"
				nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="isAcknowledged" />
						<xsd:enumeration value="timeOk" />
						<xsd:enumeration value="timeCritical" />
						<xsd:enumeration value="timeWarning" />
						<xsd:enumeration value="timeUnknown" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Type" minOccurs="1" maxOccurs="1"
				nillable="true">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="String" />
						<xsd:enumeration value="Boolean" />
						<xsd:enumeration value="Long" />
						<xsd:enumeration value="" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Value" minOccurs="1" maxOccurs="1"
				nillable="true">
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
</xsd:schema>

=== wang-shun/groundwork-trunk/groundwork-monitor-platform/monitor-apps/statusviewer/src/main/webapp/portal-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Coopyright (C) 2009 GroundWork Open Source, Inc. (GroundWork)
    All rights reserved. This program is free software; you can redistribute
    it and/or modify it under the terms of the GNU General Public License
    version 2 as published by the Free Software Foundation.
   
    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.
  
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-->
<Filters xmlns="gwos:filter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="gwos:filter FilterSchema.xsd">
	<HostFilter>
		<Name>Hosts Acknowledged</Name>
		<Label>Hosts Acknowledged</Label>
		<MonitorStatus></MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UnAcknowledged</Name>
		<Label>Hosts UnAcknowledged</Label>
		<MonitorStatus></MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</HostFilter>


	<HostFilter>
		<Name>Hosts UP for more than 2 hours</Name>
		<Label>Hosts UP for more than 2 hours</Label>
		<MonitorStatus>UP</MonitorStatus>
		<Property>
			<Name>timeUp</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNREACHABLE for more than 2 hours</Name>
		<Label>Hosts UNREACHABLE for more than 2 hours</Label>
		<MonitorStatus>UNREACHABLE</MonitorStatus>
		<Property>
			<Name>timeUnreachable</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UP for less than 5 minutes</Name>
		<Label>Hosts UP for less than 5 minutes</Label>
		<MonitorStatus>UP</MonitorStatus>
		<Property>
			<Name>timeUp</Name>
			<Type>Long</Type>
			<Value>-300000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNSCHEDULED DOWN and Acknowledged</Name>
		<Label>Hosts UNSCHEDULED DOWN and Acknowledged</Label>
		<MonitorStatus>UNSCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNSCHEDULED DOWN and Unacknowledged</Name>
		<Label>Hosts UNSCHEDULED DOWN and Unacknowledged</Label>
		<MonitorStatus>UNSCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNREACHABLE and Acknowledged</Name>
		<Label>Hosts UNREACHABLE and Acknowledged</Label>
		<MonitorStatus>UNREACHABLE</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNREACHABLE and Unacknowledged</Name>
		<Label>Hosts UNREACHABLE and Unacknowledged</Label>
		<MonitorStatus>UNREACHABLE</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UP for more than 12 hours</Name>
		<Label>Hosts UP for more than 12 hours</Label>
		<MonitorStatus>UP</MonitorStatus>
		<Property>
			<Name>timeUp</Name>
			<Type>Long</Type>
			<Value>43200000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNREACHABLE for more than 12 hours</Name>
		<Label>Hosts UNREACHABLE for more than 12 hours</Label>
		<MonitorStatus>UNREACHABLE</MonitorStatus>
		<Property>
			<Name>timeUnreachable</Name>
			<Type>Long</Type>
			<Value>43200000</Value>
		</Property>
	</HostFilter>


	<HostFilter>
		<Name>Hosts UNSCHEDULED DOWN for more than 2 hours</Name>
		<Label>Hosts UNSCHEDULED DOWN for more than 2 hours</Label>
		<MonitorStatus>UNSCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</HostFilter>


	<HostFilter>
		<Name>Hosts UNSCHEDULED DOWN for more than 12 hours</Name>
		<Label>Hosts UNSCHEDULED DOWN for more than 12 hours</Label>
		<MonitorStatus>UNSCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>43200000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts UNSCHEDULED DOWN for more than 5 minutes</Name>
		<Label>Hosts UNSCHEDULED DOWN for more than 5 minutes</Label>
		<MonitorStatus>UNSCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>300000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts SCHEDULED DOWN for more than 2 hours</Name>
		<Label>Hosts SCHEDULED DOWN for more than 2 hours</Label>
		<MonitorStatus>SCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</HostFilter>

	<HostFilter>
		<Name>Hosts SCHEDULED DOWN for more than 12 hours</Name>
		<Label>Hosts SCHEDULED DOWN for more than 12 hours</Label>
		<MonitorStatus>SCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>43200000</Value>
		</Property>
	</HostFilter>


	<HostFilter>
		<Name>Hosts SCHEDULED DOWN for more than 5 minutes</Name>
		<Label>Hosts SCHEDULED DOWN for more than 5 minutes</Label>
		<MonitorStatus>SCHEDULED DOWN</MonitorStatus>
		<Property>
			<Name>timeDown</Name>
			<Type>Long</Type>
			<Value>300000</Value>
		</Property>
	</HostFilter>


	<ServiceFilter>
		<Name>Services Acknowledged</Name>
		<Label>Services Acknowledged</Label>
		<MonitorStatus></MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</ServiceFilter>


	<ServiceFilter>
		<Name>Services UnAcknowledged</Name>
		<Label>Services UnAcknowledged</Label>
		<MonitorStatus></MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</ServiceFilter>


	<ServiceFilter>
		<Name>Services WARNING for more than 2 hours</Name>
		<Label>Services WARNING for more than 2 hours</Label>
		<MonitorStatus>WARNING</MonitorStatus>
		<Property>
			<Name>timeWarning</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNKNOWN for more than 2 hours</Name>
		<Label>Services UNKNOWN for more than 2 hours</Label>
		<MonitorStatus>UNKNOWN</MonitorStatus>
		<Property>
			<Name>timeUnknown</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services OK for more than 2 hours</Name>
		<Label>Services OK for more than 2 hours</Label>
		<MonitorStatus>OK</MonitorStatus>
		<Property>
			<Name>timeOk</Name>
			<Type>Long</Type>
			<Value>7200000</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services WARNING for less than 5 minutes</Name>
		<Label>Services WARNING for less than 5 minutes</Label>
		<MonitorStatus>WARNING</MonitorStatus>
		<Property>
			<Name>timeWarning</Name>
			<Type>Long</Type>
			<Value>-300000</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNKNOWN for less than 5 minutes</Name>
		<Label>Services UNKNOWN for less than 5 minutes</Label>
		<MonitorStatus>UNKNOWN</MonitorStatus>
		<Property>
			<Name>timeUnknown</Name>
			<Type>Long</Type>
			<Value>-300000</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNSCHEDULED CRITICAL and Acknowledged</Name>
		<Label>Services UNSCHEDULED CRITICAL and Acknowledged</Label>
		<MonitorStatus>UNSCHEDULED CRITICAL</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNSCHEDULED CRITICAL and Unacknowledged</Name>
		<Label>Services UNSCHEDULED CRITICAL and Unacknowledged</Label>
		<MonitorStatus>UNSCHEDULED CRITICAL</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services WARNING and Acknowledged</Name>
		<Label>Services WARNING and Acknowledged</Label>
		<MonitorStatus>WARNING</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services WARNING and Unacknowledged</Name>
		<Label>Services WARNING and Unacknowledged</Label>
		<MonitorStatus>WARNING</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNKNOWN and Acknowledged</Name>
		<Label>Services UNKNOWN and Acknowledged</Label>
		<MonitorStatus>UNKNOWN</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>true</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services UNKNOWN and Unacknowledged</Name>
		<Label>Services UNKNOWN and Unacknowledged</Label>
		<MonitorStatus>UNKNOWN</MonitorStatus>
		<Property>
			<Name>isAcknowledged</Name>
			<Type>Boolean</Type>
			<Value>false</Value>
		</Property>
	</ServiceFilter>

	<ServiceFilter>
		<Name>Services SCHEDULED CRITICAL for more than 2 hours</Name>
		<Label>Services SCHEDULED CRITICAL for more than 2 hours</Label>
